### ISSUE TITLE
Permission to set up similar installations

### ISSUE THREAD

**Issue by clombion** [MimiOnuoha/missing-datasets#6]
Hello, 

First of all I would like to congratulate you on your work, I love the concept even if I was not able to visit the exhibition!

I am working with the Open Knowledge Foundation on projects related to data and local democracy: specifically, one project aims to explore how libraries could become launchpads for data-driven projects by citizens trying to better document the reality of their neighborhood and the issues afflecting it.

One of the first step of this kind of project is to identify issues being discussed during citizen councils or local political councils and identify which of these issues could benefit from a data-informed discussion.

This is where your project becomes relevant: it would be a fantastic asset to be able to present this "missing data" in a form similar to the one you used in order to :

1. Create curiosity around data starting from a familiar object (filing cabinet)
2. Encourage curiosity and get citizens to explore themselves the datasets
3. Get feedback right away about the datasets the community would be interested in collecting
4. Get librarians excited to work with us as an art project is always a more exciting starting point than a powerpoint presentation :)

I will be working in France and the UK on this kind of project and I would love to be able to set up installation to yours as part of those projects, were you to grant us permission to do so. Of course we would be happy to collaborate with you to stay faithful to the idea as well as mentioning clearly your work as the inspiration for ours.

Best,

Cédric Lombion

**Comment by MimiOnuoha** [comment]
Hi Cédric, 

Thanks for reaching out! I'm happy to hear that you've found the work compelling. While the research for this project is (obviously) open-source, the presentation of the project constitutes the artwork itself. Just as you wouldn't expect to reproduce a painter's paintings, I wouldn't be pleased to see someone replicate my own artwork in this way. If you're interested in purchasing the artwork, I'm happy for us to discuss further in a private channel. Otherwise, you're welcome to cite the piece or use photographs of it to aid in the work that you're doing.

**Comment by clombion** [comment]
Thank you for responding! I believe that the concept of missing datasets is a powerful one, especially for awareness raising and engaging people around data and social issues. I have worked with artists in the past to adapt their work for projects that were in line with their artistic intent, which is why I felt free to ask you. 

I never had the intention of creating a carbon copy of your work and attribute it to my name (that would be forgery), but I'm sorry if that's what my message seemed to imply. I do not know the details of your installation, and the datasets you used are most likely not fully relevant to the communities I would be working with. 

Instead, I wanted to know if you would be interested in spreading your particular take on the concept further, and if so what form you believe it could take. We could do something completely different with the concept, but having found your take on it inspirational and fitting (as we'll be working with libraries) I wanted to make sure you could give your input, were you interested to do so.

I understand that it's not the case, and that's totally valid. We'll go in another direction and cite your work as an influence.

**Comment by MimiOnuoha** [comment]
No worries, and good luck with the project!
